// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_bus_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_5fbus_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_5fbus_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_5fbus_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_5fbus_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_5fbus_5fconfig_2eproto;
namespace messagebus {
class MalamuteClientConfig;
class MalamuteClientConfigDefaultTypeInternal;
extern MalamuteClientConfigDefaultTypeInternal _MalamuteClientConfig_default_instance_;
class MessageBusConfig;
class MessageBusConfigDefaultTypeInternal;
extern MessageBusConfigDefaultTypeInternal _MessageBusConfig_default_instance_;
class UnixSocketClientConfig;
class UnixSocketClientConfigDefaultTypeInternal;
extern UnixSocketClientConfigDefaultTypeInternal _UnixSocketClientConfig_default_instance_;
}  // namespace messagebus
PROTOBUF_NAMESPACE_OPEN
template<> ::messagebus::MalamuteClientConfig* Arena::CreateMaybeMessage<::messagebus::MalamuteClientConfig>(Arena*);
template<> ::messagebus::MessageBusConfig* Arena::CreateMaybeMessage<::messagebus::MessageBusConfig>(Arena*);
template<> ::messagebus::UnixSocketClientConfig* Arena::CreateMaybeMessage<::messagebus::UnixSocketClientConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace messagebus {

// ===================================================================

class MalamuteClientConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messagebus.MalamuteClientConfig) */ {
 public:
  MalamuteClientConfig();
  virtual ~MalamuteClientConfig();

  MalamuteClientConfig(const MalamuteClientConfig& from);
  MalamuteClientConfig(MalamuteClientConfig&& from) noexcept
    : MalamuteClientConfig() {
    *this = ::std::move(from);
  }

  inline MalamuteClientConfig& operator=(const MalamuteClientConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline MalamuteClientConfig& operator=(MalamuteClientConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MalamuteClientConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MalamuteClientConfig* internal_default_instance() {
    return reinterpret_cast<const MalamuteClientConfig*>(
               &_MalamuteClientConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MalamuteClientConfig& a, MalamuteClientConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(MalamuteClientConfig* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MalamuteClientConfig* New() const final {
    return CreateMaybeMessage<MalamuteClientConfig>(nullptr);
  }

  MalamuteClientConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MalamuteClientConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MalamuteClientConfig& from);
  void MergeFrom(const MalamuteClientConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MalamuteClientConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messagebus.MalamuteClientConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_5fbus_5fconfig_2eproto);
    return ::descriptor_table_message_5fbus_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEndPointFieldNumber = 1,
    kAgentNameFieldNumber = 2,
  };
  // string end_point = 1;
  void clear_end_point();
  const std::string& end_point() const;
  void set_end_point(const std::string& value);
  void set_end_point(std::string&& value);
  void set_end_point(const char* value);
  void set_end_point(const char* value, size_t size);
  std::string* mutable_end_point();
  std::string* release_end_point();
  void set_allocated_end_point(std::string* end_point);
  private:
  const std::string& _internal_end_point() const;
  void _internal_set_end_point(const std::string& value);
  std::string* _internal_mutable_end_point();
  public:

  // string agent_name = 2;
  void clear_agent_name();
  const std::string& agent_name() const;
  void set_agent_name(const std::string& value);
  void set_agent_name(std::string&& value);
  void set_agent_name(const char* value);
  void set_agent_name(const char* value, size_t size);
  std::string* mutable_agent_name();
  std::string* release_agent_name();
  void set_allocated_agent_name(std::string* agent_name);
  private:
  const std::string& _internal_agent_name() const;
  void _internal_set_agent_name(const std::string& value);
  std::string* _internal_mutable_agent_name();
  public:

  // @@protoc_insertion_point(class_scope:messagebus.MalamuteClientConfig)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr end_point_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr agent_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_5fbus_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class UnixSocketClientConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messagebus.UnixSocketClientConfig) */ {
 public:
  UnixSocketClientConfig();
  virtual ~UnixSocketClientConfig();

  UnixSocketClientConfig(const UnixSocketClientConfig& from);
  UnixSocketClientConfig(UnixSocketClientConfig&& from) noexcept
    : UnixSocketClientConfig() {
    *this = ::std::move(from);
  }

  inline UnixSocketClientConfig& operator=(const UnixSocketClientConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnixSocketClientConfig& operator=(UnixSocketClientConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UnixSocketClientConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UnixSocketClientConfig* internal_default_instance() {
    return reinterpret_cast<const UnixSocketClientConfig*>(
               &_UnixSocketClientConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UnixSocketClientConfig& a, UnixSocketClientConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(UnixSocketClientConfig* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UnixSocketClientConfig* New() const final {
    return CreateMaybeMessage<UnixSocketClientConfig>(nullptr);
  }

  UnixSocketClientConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UnixSocketClientConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UnixSocketClientConfig& from);
  void MergeFrom(const UnixSocketClientConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnixSocketClientConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messagebus.UnixSocketClientConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_5fbus_5fconfig_2eproto);
    return ::descriptor_table_message_5fbus_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSocketPathFieldNumber = 1,
    kAgentNameFieldNumber = 2,
  };
  // string socket_path = 1;
  void clear_socket_path();
  const std::string& socket_path() const;
  void set_socket_path(const std::string& value);
  void set_socket_path(std::string&& value);
  void set_socket_path(const char* value);
  void set_socket_path(const char* value, size_t size);
  std::string* mutable_socket_path();
  std::string* release_socket_path();
  void set_allocated_socket_path(std::string* socket_path);
  private:
  const std::string& _internal_socket_path() const;
  void _internal_set_socket_path(const std::string& value);
  std::string* _internal_mutable_socket_path();
  public:

  // string agent_name = 2;
  void clear_agent_name();
  const std::string& agent_name() const;
  void set_agent_name(const std::string& value);
  void set_agent_name(std::string&& value);
  void set_agent_name(const char* value);
  void set_agent_name(const char* value, size_t size);
  std::string* mutable_agent_name();
  std::string* release_agent_name();
  void set_allocated_agent_name(std::string* agent_name);
  private:
  const std::string& _internal_agent_name() const;
  void _internal_set_agent_name(const std::string& value);
  std::string* _internal_mutable_agent_name();
  public:

  // @@protoc_insertion_point(class_scope:messagebus.UnixSocketClientConfig)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr socket_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr agent_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_5fbus_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class MessageBusConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messagebus.MessageBusConfig) */ {
 public:
  MessageBusConfig();
  virtual ~MessageBusConfig();

  MessageBusConfig(const MessageBusConfig& from);
  MessageBusConfig(MessageBusConfig&& from) noexcept
    : MessageBusConfig() {
    *this = ::std::move(from);
  }

  inline MessageBusConfig& operator=(const MessageBusConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageBusConfig& operator=(MessageBusConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MessageBusConfig& default_instance();

  enum ParametersCase {
    kMalamuteClientConfig = 2,
    kUnixClientConfig = 3,
    PARAMETERS_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageBusConfig* internal_default_instance() {
    return reinterpret_cast<const MessageBusConfig*>(
               &_MessageBusConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MessageBusConfig& a, MessageBusConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageBusConfig* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MessageBusConfig* New() const final {
    return CreateMaybeMessage<MessageBusConfig>(nullptr);
  }

  MessageBusConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MessageBusConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MessageBusConfig& from);
  void MergeFrom(const MessageBusConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageBusConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messagebus.MessageBusConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_5fbus_5fconfig_2eproto);
    return ::descriptor_table_message_5fbus_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQueueNameFieldNumber = 1,
    kMalamuteClientConfigFieldNumber = 2,
    kUnixClientConfigFieldNumber = 3,
  };
  // string queue_name = 1;
  void clear_queue_name();
  const std::string& queue_name() const;
  void set_queue_name(const std::string& value);
  void set_queue_name(std::string&& value);
  void set_queue_name(const char* value);
  void set_queue_name(const char* value, size_t size);
  std::string* mutable_queue_name();
  std::string* release_queue_name();
  void set_allocated_queue_name(std::string* queue_name);
  private:
  const std::string& _internal_queue_name() const;
  void _internal_set_queue_name(const std::string& value);
  std::string* _internal_mutable_queue_name();
  public:

  // .messagebus.MalamuteClientConfig malamute_client_config = 2;
  bool has_malamute_client_config() const;
  private:
  bool _internal_has_malamute_client_config() const;
  public:
  void clear_malamute_client_config();
  const ::messagebus::MalamuteClientConfig& malamute_client_config() const;
  ::messagebus::MalamuteClientConfig* release_malamute_client_config();
  ::messagebus::MalamuteClientConfig* mutable_malamute_client_config();
  void set_allocated_malamute_client_config(::messagebus::MalamuteClientConfig* malamute_client_config);
  private:
  const ::messagebus::MalamuteClientConfig& _internal_malamute_client_config() const;
  ::messagebus::MalamuteClientConfig* _internal_mutable_malamute_client_config();
  public:

  // .messagebus.UnixSocketClientConfig unix_client_config = 3;
  bool has_unix_client_config() const;
  private:
  bool _internal_has_unix_client_config() const;
  public:
  void clear_unix_client_config();
  const ::messagebus::UnixSocketClientConfig& unix_client_config() const;
  ::messagebus::UnixSocketClientConfig* release_unix_client_config();
  ::messagebus::UnixSocketClientConfig* mutable_unix_client_config();
  void set_allocated_unix_client_config(::messagebus::UnixSocketClientConfig* unix_client_config);
  private:
  const ::messagebus::UnixSocketClientConfig& _internal_unix_client_config() const;
  ::messagebus::UnixSocketClientConfig* _internal_mutable_unix_client_config();
  public:

  void clear_parameters();
  ParametersCase parameters_case() const;
  // @@protoc_insertion_point(class_scope:messagebus.MessageBusConfig)
 private:
  class _Internal;
  void set_has_malamute_client_config();
  void set_has_unix_client_config();

  inline bool has_parameters() const;
  inline void clear_has_parameters();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr queue_name_;
  union ParametersUnion {
    ParametersUnion() {}
    ::messagebus::MalamuteClientConfig* malamute_client_config_;
    ::messagebus::UnixSocketClientConfig* unix_client_config_;
  } parameters_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_message_5fbus_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MalamuteClientConfig

// string end_point = 1;
inline void MalamuteClientConfig::clear_end_point() {
  end_point_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MalamuteClientConfig::end_point() const {
  // @@protoc_insertion_point(field_get:messagebus.MalamuteClientConfig.end_point)
  return _internal_end_point();
}
inline void MalamuteClientConfig::set_end_point(const std::string& value) {
  _internal_set_end_point(value);
  // @@protoc_insertion_point(field_set:messagebus.MalamuteClientConfig.end_point)
}
inline std::string* MalamuteClientConfig::mutable_end_point() {
  // @@protoc_insertion_point(field_mutable:messagebus.MalamuteClientConfig.end_point)
  return _internal_mutable_end_point();
}
inline const std::string& MalamuteClientConfig::_internal_end_point() const {
  return end_point_.GetNoArena();
}
inline void MalamuteClientConfig::_internal_set_end_point(const std::string& value) {
  
  end_point_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MalamuteClientConfig::set_end_point(std::string&& value) {
  
  end_point_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:messagebus.MalamuteClientConfig.end_point)
}
inline void MalamuteClientConfig::set_end_point(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  end_point_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messagebus.MalamuteClientConfig.end_point)
}
inline void MalamuteClientConfig::set_end_point(const char* value, size_t size) {
  
  end_point_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messagebus.MalamuteClientConfig.end_point)
}
inline std::string* MalamuteClientConfig::_internal_mutable_end_point() {
  
  return end_point_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MalamuteClientConfig::release_end_point() {
  // @@protoc_insertion_point(field_release:messagebus.MalamuteClientConfig.end_point)
  
  return end_point_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MalamuteClientConfig::set_allocated_end_point(std::string* end_point) {
  if (end_point != nullptr) {
    
  } else {
    
  }
  end_point_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), end_point);
  // @@protoc_insertion_point(field_set_allocated:messagebus.MalamuteClientConfig.end_point)
}

// string agent_name = 2;
inline void MalamuteClientConfig::clear_agent_name() {
  agent_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MalamuteClientConfig::agent_name() const {
  // @@protoc_insertion_point(field_get:messagebus.MalamuteClientConfig.agent_name)
  return _internal_agent_name();
}
inline void MalamuteClientConfig::set_agent_name(const std::string& value) {
  _internal_set_agent_name(value);
  // @@protoc_insertion_point(field_set:messagebus.MalamuteClientConfig.agent_name)
}
inline std::string* MalamuteClientConfig::mutable_agent_name() {
  // @@protoc_insertion_point(field_mutable:messagebus.MalamuteClientConfig.agent_name)
  return _internal_mutable_agent_name();
}
inline const std::string& MalamuteClientConfig::_internal_agent_name() const {
  return agent_name_.GetNoArena();
}
inline void MalamuteClientConfig::_internal_set_agent_name(const std::string& value) {
  
  agent_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MalamuteClientConfig::set_agent_name(std::string&& value) {
  
  agent_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:messagebus.MalamuteClientConfig.agent_name)
}
inline void MalamuteClientConfig::set_agent_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  agent_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messagebus.MalamuteClientConfig.agent_name)
}
inline void MalamuteClientConfig::set_agent_name(const char* value, size_t size) {
  
  agent_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messagebus.MalamuteClientConfig.agent_name)
}
inline std::string* MalamuteClientConfig::_internal_mutable_agent_name() {
  
  return agent_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MalamuteClientConfig::release_agent_name() {
  // @@protoc_insertion_point(field_release:messagebus.MalamuteClientConfig.agent_name)
  
  return agent_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MalamuteClientConfig::set_allocated_agent_name(std::string* agent_name) {
  if (agent_name != nullptr) {
    
  } else {
    
  }
  agent_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), agent_name);
  // @@protoc_insertion_point(field_set_allocated:messagebus.MalamuteClientConfig.agent_name)
}

// -------------------------------------------------------------------

// UnixSocketClientConfig

// string socket_path = 1;
inline void UnixSocketClientConfig::clear_socket_path() {
  socket_path_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UnixSocketClientConfig::socket_path() const {
  // @@protoc_insertion_point(field_get:messagebus.UnixSocketClientConfig.socket_path)
  return _internal_socket_path();
}
inline void UnixSocketClientConfig::set_socket_path(const std::string& value) {
  _internal_set_socket_path(value);
  // @@protoc_insertion_point(field_set:messagebus.UnixSocketClientConfig.socket_path)
}
inline std::string* UnixSocketClientConfig::mutable_socket_path() {
  // @@protoc_insertion_point(field_mutable:messagebus.UnixSocketClientConfig.socket_path)
  return _internal_mutable_socket_path();
}
inline const std::string& UnixSocketClientConfig::_internal_socket_path() const {
  return socket_path_.GetNoArena();
}
inline void UnixSocketClientConfig::_internal_set_socket_path(const std::string& value) {
  
  socket_path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UnixSocketClientConfig::set_socket_path(std::string&& value) {
  
  socket_path_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:messagebus.UnixSocketClientConfig.socket_path)
}
inline void UnixSocketClientConfig::set_socket_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  socket_path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messagebus.UnixSocketClientConfig.socket_path)
}
inline void UnixSocketClientConfig::set_socket_path(const char* value, size_t size) {
  
  socket_path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messagebus.UnixSocketClientConfig.socket_path)
}
inline std::string* UnixSocketClientConfig::_internal_mutable_socket_path() {
  
  return socket_path_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UnixSocketClientConfig::release_socket_path() {
  // @@protoc_insertion_point(field_release:messagebus.UnixSocketClientConfig.socket_path)
  
  return socket_path_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UnixSocketClientConfig::set_allocated_socket_path(std::string* socket_path) {
  if (socket_path != nullptr) {
    
  } else {
    
  }
  socket_path_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), socket_path);
  // @@protoc_insertion_point(field_set_allocated:messagebus.UnixSocketClientConfig.socket_path)
}

// string agent_name = 2;
inline void UnixSocketClientConfig::clear_agent_name() {
  agent_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UnixSocketClientConfig::agent_name() const {
  // @@protoc_insertion_point(field_get:messagebus.UnixSocketClientConfig.agent_name)
  return _internal_agent_name();
}
inline void UnixSocketClientConfig::set_agent_name(const std::string& value) {
  _internal_set_agent_name(value);
  // @@protoc_insertion_point(field_set:messagebus.UnixSocketClientConfig.agent_name)
}
inline std::string* UnixSocketClientConfig::mutable_agent_name() {
  // @@protoc_insertion_point(field_mutable:messagebus.UnixSocketClientConfig.agent_name)
  return _internal_mutable_agent_name();
}
inline const std::string& UnixSocketClientConfig::_internal_agent_name() const {
  return agent_name_.GetNoArena();
}
inline void UnixSocketClientConfig::_internal_set_agent_name(const std::string& value) {
  
  agent_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UnixSocketClientConfig::set_agent_name(std::string&& value) {
  
  agent_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:messagebus.UnixSocketClientConfig.agent_name)
}
inline void UnixSocketClientConfig::set_agent_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  agent_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messagebus.UnixSocketClientConfig.agent_name)
}
inline void UnixSocketClientConfig::set_agent_name(const char* value, size_t size) {
  
  agent_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messagebus.UnixSocketClientConfig.agent_name)
}
inline std::string* UnixSocketClientConfig::_internal_mutable_agent_name() {
  
  return agent_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UnixSocketClientConfig::release_agent_name() {
  // @@protoc_insertion_point(field_release:messagebus.UnixSocketClientConfig.agent_name)
  
  return agent_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UnixSocketClientConfig::set_allocated_agent_name(std::string* agent_name) {
  if (agent_name != nullptr) {
    
  } else {
    
  }
  agent_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), agent_name);
  // @@protoc_insertion_point(field_set_allocated:messagebus.UnixSocketClientConfig.agent_name)
}

// -------------------------------------------------------------------

// MessageBusConfig

// string queue_name = 1;
inline void MessageBusConfig::clear_queue_name() {
  queue_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MessageBusConfig::queue_name() const {
  // @@protoc_insertion_point(field_get:messagebus.MessageBusConfig.queue_name)
  return _internal_queue_name();
}
inline void MessageBusConfig::set_queue_name(const std::string& value) {
  _internal_set_queue_name(value);
  // @@protoc_insertion_point(field_set:messagebus.MessageBusConfig.queue_name)
}
inline std::string* MessageBusConfig::mutable_queue_name() {
  // @@protoc_insertion_point(field_mutable:messagebus.MessageBusConfig.queue_name)
  return _internal_mutable_queue_name();
}
inline const std::string& MessageBusConfig::_internal_queue_name() const {
  return queue_name_.GetNoArena();
}
inline void MessageBusConfig::_internal_set_queue_name(const std::string& value) {
  
  queue_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MessageBusConfig::set_queue_name(std::string&& value) {
  
  queue_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:messagebus.MessageBusConfig.queue_name)
}
inline void MessageBusConfig::set_queue_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  queue_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messagebus.MessageBusConfig.queue_name)
}
inline void MessageBusConfig::set_queue_name(const char* value, size_t size) {
  
  queue_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messagebus.MessageBusConfig.queue_name)
}
inline std::string* MessageBusConfig::_internal_mutable_queue_name() {
  
  return queue_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MessageBusConfig::release_queue_name() {
  // @@protoc_insertion_point(field_release:messagebus.MessageBusConfig.queue_name)
  
  return queue_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MessageBusConfig::set_allocated_queue_name(std::string* queue_name) {
  if (queue_name != nullptr) {
    
  } else {
    
  }
  queue_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), queue_name);
  // @@protoc_insertion_point(field_set_allocated:messagebus.MessageBusConfig.queue_name)
}

// .messagebus.MalamuteClientConfig malamute_client_config = 2;
inline bool MessageBusConfig::_internal_has_malamute_client_config() const {
  return parameters_case() == kMalamuteClientConfig;
}
inline bool MessageBusConfig::has_malamute_client_config() const {
  return _internal_has_malamute_client_config();
}
inline void MessageBusConfig::set_has_malamute_client_config() {
  _oneof_case_[0] = kMalamuteClientConfig;
}
inline void MessageBusConfig::clear_malamute_client_config() {
  if (_internal_has_malamute_client_config()) {
    delete parameters_.malamute_client_config_;
    clear_has_parameters();
  }
}
inline ::messagebus::MalamuteClientConfig* MessageBusConfig::release_malamute_client_config() {
  // @@protoc_insertion_point(field_release:messagebus.MessageBusConfig.malamute_client_config)
  if (_internal_has_malamute_client_config()) {
    clear_has_parameters();
      ::messagebus::MalamuteClientConfig* temp = parameters_.malamute_client_config_;
    parameters_.malamute_client_config_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::messagebus::MalamuteClientConfig& MessageBusConfig::_internal_malamute_client_config() const {
  return _internal_has_malamute_client_config()
      ? *parameters_.malamute_client_config_
      : *reinterpret_cast< ::messagebus::MalamuteClientConfig*>(&::messagebus::_MalamuteClientConfig_default_instance_);
}
inline const ::messagebus::MalamuteClientConfig& MessageBusConfig::malamute_client_config() const {
  // @@protoc_insertion_point(field_get:messagebus.MessageBusConfig.malamute_client_config)
  return _internal_malamute_client_config();
}
inline ::messagebus::MalamuteClientConfig* MessageBusConfig::_internal_mutable_malamute_client_config() {
  if (!_internal_has_malamute_client_config()) {
    clear_parameters();
    set_has_malamute_client_config();
    parameters_.malamute_client_config_ = CreateMaybeMessage< ::messagebus::MalamuteClientConfig >(
        GetArenaNoVirtual());
  }
  return parameters_.malamute_client_config_;
}
inline ::messagebus::MalamuteClientConfig* MessageBusConfig::mutable_malamute_client_config() {
  // @@protoc_insertion_point(field_mutable:messagebus.MessageBusConfig.malamute_client_config)
  return _internal_mutable_malamute_client_config();
}

// .messagebus.UnixSocketClientConfig unix_client_config = 3;
inline bool MessageBusConfig::_internal_has_unix_client_config() const {
  return parameters_case() == kUnixClientConfig;
}
inline bool MessageBusConfig::has_unix_client_config() const {
  return _internal_has_unix_client_config();
}
inline void MessageBusConfig::set_has_unix_client_config() {
  _oneof_case_[0] = kUnixClientConfig;
}
inline void MessageBusConfig::clear_unix_client_config() {
  if (_internal_has_unix_client_config()) {
    delete parameters_.unix_client_config_;
    clear_has_parameters();
  }
}
inline ::messagebus::UnixSocketClientConfig* MessageBusConfig::release_unix_client_config() {
  // @@protoc_insertion_point(field_release:messagebus.MessageBusConfig.unix_client_config)
  if (_internal_has_unix_client_config()) {
    clear_has_parameters();
      ::messagebus::UnixSocketClientConfig* temp = parameters_.unix_client_config_;
    parameters_.unix_client_config_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::messagebus::UnixSocketClientConfig& MessageBusConfig::_internal_unix_client_config() const {
  return _internal_has_unix_client_config()
      ? *parameters_.unix_client_config_
      : *reinterpret_cast< ::messagebus::UnixSocketClientConfig*>(&::messagebus::_UnixSocketClientConfig_default_instance_);
}
inline const ::messagebus::UnixSocketClientConfig& MessageBusConfig::unix_client_config() const {
  // @@protoc_insertion_point(field_get:messagebus.MessageBusConfig.unix_client_config)
  return _internal_unix_client_config();
}
inline ::messagebus::UnixSocketClientConfig* MessageBusConfig::_internal_mutable_unix_client_config() {
  if (!_internal_has_unix_client_config()) {
    clear_parameters();
    set_has_unix_client_config();
    parameters_.unix_client_config_ = CreateMaybeMessage< ::messagebus::UnixSocketClientConfig >(
        GetArenaNoVirtual());
  }
  return parameters_.unix_client_config_;
}
inline ::messagebus::UnixSocketClientConfig* MessageBusConfig::mutable_unix_client_config() {
  // @@protoc_insertion_point(field_mutable:messagebus.MessageBusConfig.unix_client_config)
  return _internal_mutable_unix_client_config();
}

inline bool MessageBusConfig::has_parameters() const {
  return parameters_case() != PARAMETERS_NOT_SET;
}
inline void MessageBusConfig::clear_has_parameters() {
  _oneof_case_[0] = PARAMETERS_NOT_SET;
}
inline MessageBusConfig::ParametersCase MessageBusConfig::parameters_case() const {
  return MessageBusConfig::ParametersCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messagebus

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_5fbus_5fconfig_2eproto
