// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_bus_config.proto

#include "message_bus_config_pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_message_5fbus_5fconfig_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_message_5fbus_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MalamuteClientConfig;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_message_5fbus_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_UnixSocketClientConfig;
}  // namespace protobuf_message_5fbus_5fconfig_2eproto
namespace messagebus {
class MalamuteClientConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MalamuteClientConfig>
      _instance;
} _MalamuteClientConfig_default_instance_;
class UnixSocketClientConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UnixSocketClientConfig>
      _instance;
} _UnixSocketClientConfig_default_instance_;
class MessageBusConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MessageBusConfig>
      _instance;
  const ::messagebus::MalamuteClientConfig* malamute_client_config_;
  const ::messagebus::UnixSocketClientConfig* unix_client_config_;
} _MessageBusConfig_default_instance_;
}  // namespace messagebus
namespace protobuf_message_5fbus_5fconfig_2eproto {
static void InitDefaultsMalamuteClientConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::messagebus::_MalamuteClientConfig_default_instance_;
    new (ptr) ::messagebus::MalamuteClientConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::messagebus::MalamuteClientConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MalamuteClientConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMalamuteClientConfig}, {}};

static void InitDefaultsUnixSocketClientConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::messagebus::_UnixSocketClientConfig_default_instance_;
    new (ptr) ::messagebus::UnixSocketClientConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::messagebus::UnixSocketClientConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UnixSocketClientConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUnixSocketClientConfig}, {}};

static void InitDefaultsMessageBusConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::messagebus::_MessageBusConfig_default_instance_;
    new (ptr) ::messagebus::MessageBusConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::messagebus::MessageBusConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_MessageBusConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsMessageBusConfig}, {
      &protobuf_message_5fbus_5fconfig_2eproto::scc_info_MalamuteClientConfig.base,
      &protobuf_message_5fbus_5fconfig_2eproto::scc_info_UnixSocketClientConfig.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MalamuteClientConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UnixSocketClientConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MessageBusConfig.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MalamuteClientConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MalamuteClientConfig, end_point_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MalamuteClientConfig, agent_name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::UnixSocketClientConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::UnixSocketClientConfig, socket_path_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::UnixSocketClientConfig, agent_name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MessageBusConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MessageBusConfig, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MessageBusConfig, queue_name_),
  offsetof(::messagebus::MessageBusConfigDefaultTypeInternal, malamute_client_config_),
  offsetof(::messagebus::MessageBusConfigDefaultTypeInternal, unix_client_config_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::messagebus::MessageBusConfig, parameters_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::messagebus::MalamuteClientConfig)},
  { 7, -1, sizeof(::messagebus::UnixSocketClientConfig)},
  { 14, -1, sizeof(::messagebus::MessageBusConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::messagebus::_MalamuteClientConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::messagebus::_UnixSocketClientConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::messagebus::_MessageBusConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "message_bus_config.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030message_bus_config.proto\022\nmessagebus\"="
      "\n\024MalamuteClientConfig\022\021\n\tend_point\030\001 \001("
      "\t\022\022\n\nagent_name\030\002 \001(\t\"A\n\026UnixSocketClien"
      "tConfig\022\023\n\013socket_path\030\001 \001(\t\022\022\n\nagent_na"
      "me\030\002 \001(\t\"\272\001\n\020MessageBusConfig\022\022\n\nqueue_n"
      "ame\030\001 \001(\t\022B\n\026malamute_client_config\030\002 \001("
      "\0132 .messagebus.MalamuteClientConfigH\000\022@\n"
      "\022unix_client_config\030\003 \001(\0132\".messagebus.U"
      "nixSocketClientConfigH\000B\014\n\nparametersb\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 365);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message_bus_config.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_message_5fbus_5fconfig_2eproto
namespace messagebus {

// ===================================================================

void MalamuteClientConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MalamuteClientConfig::kEndPointFieldNumber;
const int MalamuteClientConfig::kAgentNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MalamuteClientConfig::MalamuteClientConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_message_5fbus_5fconfig_2eproto::scc_info_MalamuteClientConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:messagebus.MalamuteClientConfig)
}
MalamuteClientConfig::MalamuteClientConfig(const MalamuteClientConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  end_point_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.end_point().size() > 0) {
    end_point_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.end_point_);
  }
  agent_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.agent_name().size() > 0) {
    agent_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.agent_name_);
  }
  // @@protoc_insertion_point(copy_constructor:messagebus.MalamuteClientConfig)
}

void MalamuteClientConfig::SharedCtor() {
  end_point_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  agent_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MalamuteClientConfig::~MalamuteClientConfig() {
  // @@protoc_insertion_point(destructor:messagebus.MalamuteClientConfig)
  SharedDtor();
}

void MalamuteClientConfig::SharedDtor() {
  end_point_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  agent_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MalamuteClientConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MalamuteClientConfig::descriptor() {
  ::protobuf_message_5fbus_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_5fbus_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MalamuteClientConfig& MalamuteClientConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_message_5fbus_5fconfig_2eproto::scc_info_MalamuteClientConfig.base);
  return *internal_default_instance();
}


void MalamuteClientConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:messagebus.MalamuteClientConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  end_point_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  agent_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool MalamuteClientConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:messagebus.MalamuteClientConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string end_point = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_end_point()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->end_point().data(), static_cast<int>(this->end_point().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messagebus.MalamuteClientConfig.end_point"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string agent_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_agent_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->agent_name().data(), static_cast<int>(this->agent_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messagebus.MalamuteClientConfig.agent_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:messagebus.MalamuteClientConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:messagebus.MalamuteClientConfig)
  return false;
#undef DO_
}

void MalamuteClientConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:messagebus.MalamuteClientConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string end_point = 1;
  if (this->end_point().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->end_point().data(), static_cast<int>(this->end_point().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.MalamuteClientConfig.end_point");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->end_point(), output);
  }

  // string agent_name = 2;
  if (this->agent_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->agent_name().data(), static_cast<int>(this->agent_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.MalamuteClientConfig.agent_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->agent_name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:messagebus.MalamuteClientConfig)
}

::google::protobuf::uint8* MalamuteClientConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:messagebus.MalamuteClientConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string end_point = 1;
  if (this->end_point().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->end_point().data(), static_cast<int>(this->end_point().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.MalamuteClientConfig.end_point");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->end_point(), target);
  }

  // string agent_name = 2;
  if (this->agent_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->agent_name().data(), static_cast<int>(this->agent_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.MalamuteClientConfig.agent_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->agent_name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messagebus.MalamuteClientConfig)
  return target;
}

size_t MalamuteClientConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messagebus.MalamuteClientConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string end_point = 1;
  if (this->end_point().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->end_point());
  }

  // string agent_name = 2;
  if (this->agent_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->agent_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MalamuteClientConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:messagebus.MalamuteClientConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const MalamuteClientConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MalamuteClientConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:messagebus.MalamuteClientConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:messagebus.MalamuteClientConfig)
    MergeFrom(*source);
  }
}

void MalamuteClientConfig::MergeFrom(const MalamuteClientConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:messagebus.MalamuteClientConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.end_point().size() > 0) {

    end_point_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.end_point_);
  }
  if (from.agent_name().size() > 0) {

    agent_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.agent_name_);
  }
}

void MalamuteClientConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:messagebus.MalamuteClientConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MalamuteClientConfig::CopyFrom(const MalamuteClientConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messagebus.MalamuteClientConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MalamuteClientConfig::IsInitialized() const {
  return true;
}

void MalamuteClientConfig::Swap(MalamuteClientConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MalamuteClientConfig::InternalSwap(MalamuteClientConfig* other) {
  using std::swap;
  end_point_.Swap(&other->end_point_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  agent_name_.Swap(&other->agent_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MalamuteClientConfig::GetMetadata() const {
  protobuf_message_5fbus_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_5fbus_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UnixSocketClientConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UnixSocketClientConfig::kSocketPathFieldNumber;
const int UnixSocketClientConfig::kAgentNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UnixSocketClientConfig::UnixSocketClientConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_message_5fbus_5fconfig_2eproto::scc_info_UnixSocketClientConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:messagebus.UnixSocketClientConfig)
}
UnixSocketClientConfig::UnixSocketClientConfig(const UnixSocketClientConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  socket_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.socket_path().size() > 0) {
    socket_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.socket_path_);
  }
  agent_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.agent_name().size() > 0) {
    agent_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.agent_name_);
  }
  // @@protoc_insertion_point(copy_constructor:messagebus.UnixSocketClientConfig)
}

void UnixSocketClientConfig::SharedCtor() {
  socket_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  agent_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

UnixSocketClientConfig::~UnixSocketClientConfig() {
  // @@protoc_insertion_point(destructor:messagebus.UnixSocketClientConfig)
  SharedDtor();
}

void UnixSocketClientConfig::SharedDtor() {
  socket_path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  agent_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UnixSocketClientConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UnixSocketClientConfig::descriptor() {
  ::protobuf_message_5fbus_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_5fbus_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UnixSocketClientConfig& UnixSocketClientConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_message_5fbus_5fconfig_2eproto::scc_info_UnixSocketClientConfig.base);
  return *internal_default_instance();
}


void UnixSocketClientConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:messagebus.UnixSocketClientConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  socket_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  agent_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool UnixSocketClientConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:messagebus.UnixSocketClientConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string socket_path = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_socket_path()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->socket_path().data(), static_cast<int>(this->socket_path().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messagebus.UnixSocketClientConfig.socket_path"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string agent_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_agent_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->agent_name().data(), static_cast<int>(this->agent_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messagebus.UnixSocketClientConfig.agent_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:messagebus.UnixSocketClientConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:messagebus.UnixSocketClientConfig)
  return false;
#undef DO_
}

void UnixSocketClientConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:messagebus.UnixSocketClientConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string socket_path = 1;
  if (this->socket_path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->socket_path().data(), static_cast<int>(this->socket_path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.UnixSocketClientConfig.socket_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->socket_path(), output);
  }

  // string agent_name = 2;
  if (this->agent_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->agent_name().data(), static_cast<int>(this->agent_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.UnixSocketClientConfig.agent_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->agent_name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:messagebus.UnixSocketClientConfig)
}

::google::protobuf::uint8* UnixSocketClientConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:messagebus.UnixSocketClientConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string socket_path = 1;
  if (this->socket_path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->socket_path().data(), static_cast<int>(this->socket_path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.UnixSocketClientConfig.socket_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->socket_path(), target);
  }

  // string agent_name = 2;
  if (this->agent_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->agent_name().data(), static_cast<int>(this->agent_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.UnixSocketClientConfig.agent_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->agent_name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messagebus.UnixSocketClientConfig)
  return target;
}

size_t UnixSocketClientConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messagebus.UnixSocketClientConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string socket_path = 1;
  if (this->socket_path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->socket_path());
  }

  // string agent_name = 2;
  if (this->agent_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->agent_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UnixSocketClientConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:messagebus.UnixSocketClientConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const UnixSocketClientConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UnixSocketClientConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:messagebus.UnixSocketClientConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:messagebus.UnixSocketClientConfig)
    MergeFrom(*source);
  }
}

void UnixSocketClientConfig::MergeFrom(const UnixSocketClientConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:messagebus.UnixSocketClientConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.socket_path().size() > 0) {

    socket_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.socket_path_);
  }
  if (from.agent_name().size() > 0) {

    agent_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.agent_name_);
  }
}

void UnixSocketClientConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:messagebus.UnixSocketClientConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnixSocketClientConfig::CopyFrom(const UnixSocketClientConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messagebus.UnixSocketClientConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnixSocketClientConfig::IsInitialized() const {
  return true;
}

void UnixSocketClientConfig::Swap(UnixSocketClientConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UnixSocketClientConfig::InternalSwap(UnixSocketClientConfig* other) {
  using std::swap;
  socket_path_.Swap(&other->socket_path_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  agent_name_.Swap(&other->agent_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UnixSocketClientConfig::GetMetadata() const {
  protobuf_message_5fbus_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_5fbus_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MessageBusConfig::InitAsDefaultInstance() {
  ::messagebus::_MessageBusConfig_default_instance_.malamute_client_config_ = const_cast< ::messagebus::MalamuteClientConfig*>(
      ::messagebus::MalamuteClientConfig::internal_default_instance());
  ::messagebus::_MessageBusConfig_default_instance_.unix_client_config_ = const_cast< ::messagebus::UnixSocketClientConfig*>(
      ::messagebus::UnixSocketClientConfig::internal_default_instance());
}
void MessageBusConfig::set_allocated_malamute_client_config(::messagebus::MalamuteClientConfig* malamute_client_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_parameters();
  if (malamute_client_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      malamute_client_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, malamute_client_config, submessage_arena);
    }
    set_has_malamute_client_config();
    parameters_.malamute_client_config_ = malamute_client_config;
  }
  // @@protoc_insertion_point(field_set_allocated:messagebus.MessageBusConfig.malamute_client_config)
}
void MessageBusConfig::set_allocated_unix_client_config(::messagebus::UnixSocketClientConfig* unix_client_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_parameters();
  if (unix_client_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      unix_client_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, unix_client_config, submessage_arena);
    }
    set_has_unix_client_config();
    parameters_.unix_client_config_ = unix_client_config;
  }
  // @@protoc_insertion_point(field_set_allocated:messagebus.MessageBusConfig.unix_client_config)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageBusConfig::kQueueNameFieldNumber;
const int MessageBusConfig::kMalamuteClientConfigFieldNumber;
const int MessageBusConfig::kUnixClientConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageBusConfig::MessageBusConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_message_5fbus_5fconfig_2eproto::scc_info_MessageBusConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:messagebus.MessageBusConfig)
}
MessageBusConfig::MessageBusConfig(const MessageBusConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  queue_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.queue_name().size() > 0) {
    queue_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.queue_name_);
  }
  clear_has_parameters();
  switch (from.parameters_case()) {
    case kMalamuteClientConfig: {
      mutable_malamute_client_config()->::messagebus::MalamuteClientConfig::MergeFrom(from.malamute_client_config());
      break;
    }
    case kUnixClientConfig: {
      mutable_unix_client_config()->::messagebus::UnixSocketClientConfig::MergeFrom(from.unix_client_config());
      break;
    }
    case PARAMETERS_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:messagebus.MessageBusConfig)
}

void MessageBusConfig::SharedCtor() {
  queue_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parameters();
}

MessageBusConfig::~MessageBusConfig() {
  // @@protoc_insertion_point(destructor:messagebus.MessageBusConfig)
  SharedDtor();
}

void MessageBusConfig::SharedDtor() {
  queue_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_parameters()) {
    clear_parameters();
  }
}

void MessageBusConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MessageBusConfig::descriptor() {
  ::protobuf_message_5fbus_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_5fbus_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MessageBusConfig& MessageBusConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_message_5fbus_5fconfig_2eproto::scc_info_MessageBusConfig.base);
  return *internal_default_instance();
}


void MessageBusConfig::clear_parameters() {
// @@protoc_insertion_point(one_of_clear_start:messagebus.MessageBusConfig)
  switch (parameters_case()) {
    case kMalamuteClientConfig: {
      delete parameters_.malamute_client_config_;
      break;
    }
    case kUnixClientConfig: {
      delete parameters_.unix_client_config_;
      break;
    }
    case PARAMETERS_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = PARAMETERS_NOT_SET;
}


void MessageBusConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:messagebus.MessageBusConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  queue_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_parameters();
  _internal_metadata_.Clear();
}

bool MessageBusConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:messagebus.MessageBusConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string queue_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_queue_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->queue_name().data(), static_cast<int>(this->queue_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messagebus.MessageBusConfig.queue_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .messagebus.MalamuteClientConfig malamute_client_config = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_malamute_client_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .messagebus.UnixSocketClientConfig unix_client_config = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_unix_client_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:messagebus.MessageBusConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:messagebus.MessageBusConfig)
  return false;
#undef DO_
}

void MessageBusConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:messagebus.MessageBusConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string queue_name = 1;
  if (this->queue_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->queue_name().data(), static_cast<int>(this->queue_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.MessageBusConfig.queue_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->queue_name(), output);
  }

  // .messagebus.MalamuteClientConfig malamute_client_config = 2;
  if (has_malamute_client_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_malamute_client_config(), output);
  }

  // .messagebus.UnixSocketClientConfig unix_client_config = 3;
  if (has_unix_client_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_unix_client_config(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:messagebus.MessageBusConfig)
}

::google::protobuf::uint8* MessageBusConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:messagebus.MessageBusConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string queue_name = 1;
  if (this->queue_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->queue_name().data(), static_cast<int>(this->queue_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messagebus.MessageBusConfig.queue_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->queue_name(), target);
  }

  // .messagebus.MalamuteClientConfig malamute_client_config = 2;
  if (has_malamute_client_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_malamute_client_config(), deterministic, target);
  }

  // .messagebus.UnixSocketClientConfig unix_client_config = 3;
  if (has_unix_client_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_unix_client_config(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messagebus.MessageBusConfig)
  return target;
}

size_t MessageBusConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messagebus.MessageBusConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string queue_name = 1;
  if (this->queue_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->queue_name());
  }

  switch (parameters_case()) {
    // .messagebus.MalamuteClientConfig malamute_client_config = 2;
    case kMalamuteClientConfig: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *parameters_.malamute_client_config_);
      break;
    }
    // .messagebus.UnixSocketClientConfig unix_client_config = 3;
    case kUnixClientConfig: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *parameters_.unix_client_config_);
      break;
    }
    case PARAMETERS_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MessageBusConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:messagebus.MessageBusConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const MessageBusConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MessageBusConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:messagebus.MessageBusConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:messagebus.MessageBusConfig)
    MergeFrom(*source);
  }
}

void MessageBusConfig::MergeFrom(const MessageBusConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:messagebus.MessageBusConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.queue_name().size() > 0) {

    queue_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.queue_name_);
  }
  switch (from.parameters_case()) {
    case kMalamuteClientConfig: {
      mutable_malamute_client_config()->::messagebus::MalamuteClientConfig::MergeFrom(from.malamute_client_config());
      break;
    }
    case kUnixClientConfig: {
      mutable_unix_client_config()->::messagebus::UnixSocketClientConfig::MergeFrom(from.unix_client_config());
      break;
    }
    case PARAMETERS_NOT_SET: {
      break;
    }
  }
}

void MessageBusConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:messagebus.MessageBusConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageBusConfig::CopyFrom(const MessageBusConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messagebus.MessageBusConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageBusConfig::IsInitialized() const {
  return true;
}

void MessageBusConfig::Swap(MessageBusConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageBusConfig::InternalSwap(MessageBusConfig* other) {
  using std::swap;
  queue_name_.Swap(&other->queue_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(parameters_, other->parameters_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MessageBusConfig::GetMetadata() const {
  protobuf_message_5fbus_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_5fbus_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace messagebus
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::messagebus::MalamuteClientConfig* Arena::CreateMaybeMessage< ::messagebus::MalamuteClientConfig >(Arena* arena) {
  return Arena::CreateInternal< ::messagebus::MalamuteClientConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::messagebus::UnixSocketClientConfig* Arena::CreateMaybeMessage< ::messagebus::UnixSocketClientConfig >(Arena* arena) {
  return Arena::CreateInternal< ::messagebus::UnixSocketClientConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::messagebus::MessageBusConfig* Arena::CreateMaybeMessage< ::messagebus::MessageBusConfig >(Arena* arena) {
  return Arena::CreateInternal< ::messagebus::MessageBusConfig >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
